### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by wenzhi-zhang** [jkulhanek/robot-visual-navigation#12] opened 2022-05-11 02:08 UTC
when l train model in real world dataset,l meet some error and the final result is differ from the paper.
this is the error during the training
![image](https://user-images.githubusercontent.com/93539502/167754452-ab81b6f6-29d0-4eba-8cca-de3c7234cb47.png)
and this is the training result
![image](https://user-images.githubusercontent.com/93539502/167754668-9d405c4b-0cbf-4399-ab04-e6626576044b.png)

**Comment by jkulhanek** [comment] 2022-05-12 07:36
Thanks for sharing. I will take a look at it as soon as I find some time. I guess the error is in unreal auxiliary tasks. I refactored the deeprl-pytorch package since the release of the paper and I might have caused some errors.

**Comment by GongYanfu** [comment] 2022-06-15 11:01
Hello, are you still using the author's model? Have you used the author's code on a real robot? Can it run smoothly on a robot? Can it run successfully on the server?
Recently I‘m trying to use the pre-trained model by author on my turtlrbot2, but I cannt run it smoothly. Fisrtly there some errors in ros workspace and then I resolved it, but now there are some errors in python folder such as agent.py, model.py. 
So I want to know if you run it successfully? 
I'd be grateful if you can answer my question. Thanks

**Comment by jkulhanek** [comment] 2022-07-13 09:31
The source code published in the repository is not the original one I used for the experiments. When I was cleaning it perhaps I added a bug causing the auxiliary tasks not to work properly. I will try to compare the original source code side by side with the new one and locate the bug. If anyone wants it I can also share with you the original source code (but it is a bit messy).

**Comment by jkulhanek** [comment] 2022-07-13 09:32
Please post any errors you may encounter (open a new issue for the error) so I can look at them.

**Comment by GongYanfu** [comment] 2022-07-13 12:47
> 存储库中发布的源代码不是我用于实验的原始代码。当我清理它时，也许我添加了一个导致辅助任务无法正常工作的错误。我将尝试将原始源代码与新源代码并排比较并定位错误。如果有人想要它，我也可以与您分享原始源代码（但有点乱）。

can you share  the original source code here? if you can , upload it to github, thank you.

**Comment by jkulhanek** [comment] 2022-07-13 13:33
The source code is here: https://data.ciirc.cvut.cz/public/projects/2021RealWorldNavigation/checkpoints/old-rw-nav.zip
The corresponding version of deep-rl-pytorch should be 0.3.0!

**Comment by jkulhanek** [comment] 2022-07-13 13:41
I guess the deep-rl-pytorch version is even older. I will try to find it.

**Comment by jkulhanek** [comment] 2022-07-13 13:45
Ok, please try 0.2.7

**Comment by GongYanfu** [comment] 2022-07-14 07:43
> Ok, please try 0.2.7

There is no deep-rl-pytorch V0.2.7, I found the earliest version is 0.3.1

**Comment by jkulhanek** [comment] 2022-07-14 08:21
What is the output of `pip install deep-rl==0.2.7`?

**Comment by GongYanfu** [comment] 2022-07-18 01:25
> The source code published in the repository is not the original one I used for the experiments. When I was cleaning it perhaps I added a bug causing the auxiliary tasks not to work properly. I will try to compare the original source code side by side with the new one and locate the bug. If anyone wants it I can also share with you the original source code (but it is a bit messy).

I think the error occurs in the code of  your deep-rl-pytorch repo, not the code of robot-visual-navigation?

**Comment by jkulhanek** [comment] 2022-07-18 07:16
I agree, therefore use the older deep-rl-pytorch version.

**Comment by GongYanfu** [comment] 2022-07-18 09:28
I used all of the other version of deep-rl-pytorch. if I use v0.3.6, there are same problem. If I use other older versions, there will be new problem.

**Comment by jkulhanek** [comment] 2022-07-18 09:29
You should try 0.2.7.

**Comment by GongYanfu** [comment] 2022-07-18 09:34
I dont use it in the old-rvn, I'm trying to use deep-rl in the newest rvn. I cannt use v0.2.7, its too low.

**Comment by jkulhanek** [comment] 2022-07-18 09:51
Ok. I know about the bug and will try to find the cause of the problem with the current version when I have some time. Meanwhile please use the older version of this repo with the older version of deep-rl-pytorch to reproduce the paper's results.

**Comment by GongYanfu** [comment] 2022-07-22 08:20
It seems that the training results are still somewhat abnormal by running the code of old-version repo, where the red represents the experiment ”turtlebot“, and the green represents the "turtlebot-a2c"
![image](https://user-images.githubusercontent.com/46698455/180395552-50aa81ca-ca87-4b2a-973e-8d3c9dca822d.png)

**Comment by jkulhanek** [comment] 2022-07-22 09:42
I have merged the old source code to the current version (PR  #15). The issue should be resolved now. I tried training the turtlebot experiments and it is working now. 

If you still encounter problems with training please open a new issue.

**Closed as completed by jkulhanek** 2022-07-22 09:42 UTC
